### ISSUE TITLE
Allow empty skippedSchemas with igluctl deploy

### ISSUE THREAD

**Issue by TravisHardman** [snowplow/igluctl#136]
I'm trying to get igluctl deploy running for the first time and running into issues with the `skippedSchemas` property in the config file.

If the property is missing (as it is in the example config), I get an error: "Configuration is invalid: Could not parse config: DecodingFailure at .lint.skippedSchemas: Attempt to decode value on failed cursor"

```
"lint": {
    "skipWarnings": false
    "includedChecks": [
      "rootObject"
      "unknownFormats"
      "numericMinMax"
      "stringLength"
      "optionalNull"
      "description"
      "stringMaxLengthRange"
    ]
}
```

Looking at the code, it appears to expect a list of strings. If I add an empty list, I get an error: "Configuration is invalid: Could not parse config: DecodingFailure at : Message(INVALID_IGLUURI - check schema are comma separated in iglu:<URI1>,iglu:<URI2> format)"

```
"lint": {
  "skipWarnings": false
  "skippedSchemas": []
  "includedChecks": [
    "rootObject"
    "unknownFormats"
    "numericMinMax"
    "stringLength"
    "optionalNull"
    "description"
    "stringMaxLengthRange"
  ]
}
```

Finally I tried adding a made up schema URI, but that gives the same error: "Configuration is invalid: Could not parse config: DecodingFailure at : Message(INVALID_IGLUURI - check schema are comma separated in iglu:<URI1>,iglu:<URI2> format)"

```
"lint": {
  "skipWarnings": false
  "skippedSchemas": [
    "iglu:com.example/not/a/real/schema/1-0-0"
  ]
  "includedChecks": [
    "rootObject"
    "unknownFormats"
    "numericMinMax"
    "stringLength"
    "optionalNull"
    "description"
    "stringMaxLengthRange"
  ]
}
```

The only way I have been able to get past the linting step on a deploy is to put one of my real schemas into the "skippedSchemas" field. I don't want to skip any of my schemas, but I don't see another workaround aside from making up a fake schema to skip every time.

Is this a bug or am I misunderstanding the functionality?

**Comment by benjben** [comment]
Hi @TravisHardman ,

For next questions, please use our [discourse](https://discourse.snowplow.io/).

I'll assume that you're using latest version of `igluctl`, i.e. `0.10.1`.

Indeed it seems that you found a bug, thank you !

The reason is that the [same function](https://github.com/snowplow/igluctl/blob/0.10.1/src/main/scala/com.snowplowanalytics.iglu/ctl/commands/Lint.scala#L153) is used:
1. When using `igluctl lint --skip--schemas`
2. When using `igluctl static deploy`

This function expects a non-empty list. In the first case this is fine as we would not add `--skip--schemas` without at least one schema, but in the second case this is not right as we should be able to have an empty list.

Let me open a PR with the fix.

**Comment by TravisHardman** [comment]
Thanks. Yes, I'm using the latest version.

Sorry for the confusion. I was pretty sure it was a bug, which is why I reported it here. Next time I'll use discourse.

**Comment by benjben** [comment]
No worries at all, it was indeed a bug!

We've released `0.10.2-rc1` with the fix, could you try and let us know if it solves your problem please ? You can find it [here](https://github.com/snowplow/igluctl/releases/download/0.10.2-rc1/igluctl_0.10.2-rc1.zip).

**Comment by TravisHardman** [comment]
Works great! Thank you for the quick fix.

**Comment by benjben** [comment]
Thank you for testing ! `0.10.2` has been [released](https://github.com/snowplow/igluctl/releases/tag/0.10.2).
